# Generated by Django 5.0.1 on 2025-06-06 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task_management", "0014_alter_task_optimizer_alter_task_start_date"),
        ("tasks", "0005_project_productbackend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "actual_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="实际消耗总额",
                    ),
                ),
                (
                    "fb_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="FB消耗",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="差异金额",
                    ),
                ),
                (
                    "difference_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="差异百分比",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待对账"),
                            ("completed", "完成对账"),
                            ("exception", "异常对账"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="对账状态",
                    ),
                ),
                (
                    "is_manually_confirmed",
                    models.BooleanField(default=False, verbose_name="是否手动确认"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_records",
                        to="tasks.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_records",
                        to="task_management.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "对账记录",
                "verbose_name_plural": "对账记录",
                "ordering": ["-year", "-month", "project__ProjectName", "task__name"],
                "unique_together": {("year", "month", "task")},
            },
        ),
        migrations.CreateModel(
            name="ReconciliationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("confirm", "手动确认"),
                            ("system_confirm", "系统确认"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "等待对账"),
                            ("completed", "完成对账"),
                            ("exception", "异常对账"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="旧状态",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待对账"),
                            ("completed", "完成对账"),
                            ("exception", "异常对账"),
                        ],
                        max_length=20,
                        verbose_name="新状态",
                    ),
                ),
                (
                    "old_fb_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="旧FB消耗",
                    ),
                ),
                (
                    "new_fb_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="新FB消耗",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="差异金额",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "operated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="reconciliation_management.reconciliationrecord",
                        verbose_name="对账记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "对账历史",
                "verbose_name_plural": "对账历史",
                "ordering": ["-operated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="reconciliation_attachments/%Y/%m/",
                        verbose_name="附件文件",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_size", models.IntegerField(verbose_name="文件大小(KB)")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reconciliation_management.reconciliationrecord",
                        verbose_name="对账记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "对账附件",
                "verbose_name_plural": "对账附件",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
