# Generated by Django 5.0.1 on 2025-03-13 08:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organize", "0001_initial"),
        ("tasks", "0002_alter_project_options_project_pixel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "advert_name",
                    models.CharField(max_length=200, verbose_name="广告命名"),
                ),
                ("kpi", models.CharField(max_length=500, verbose_name="KPI")),
                ("product_info", models.TextField(blank=True, verbose_name="产品信息")),
                (
                    "backend",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="产品后台"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="开始日期"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organize.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operated_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="运营负责人",
                    ),
                ),
                (
                    "optimizer",
                    models.ManyToManyField(
                        related_name="optimized_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="优化师",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.taskstatus",
                        verbose_name="任务状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
