# Generated by Django 5.0.1 on 2025-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
    ]
