# Generated by Django 5.0.1 on 2025-03-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0002_task_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_active",
        ),
    ]
