# Generated by Django 5.0.1 on 2025-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0003_remove_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="daily_report_url",
            field=models.URLField(
                blank=True,
                help_text="任务日报链接，可以为空",
                max_length=500,
                verbose_name="日报链接",
            ),
        ),
    ]
