# Generated by Django 5.0.1 on 2025-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0004_add_daily_report_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_my_task", "Can view my tasks (查看我的任务)"),
                    (
                        "view_department_task",
                        "Can view department tasks (查看部门任务)",
                    ),
                    ("view_all_task", "Can view all tasks (查看所有任务)"),
                ],
                "verbose_name": "任务",
                "verbose_name_plural": "任务列表",
            },
        ),
    ]
