# Generated by Django 5.1.4 on 2025-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pixel",
            field=models.TextField(
                blank=True, help_text="广告像素代码", null=True, verbose_name="广告像素"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="publish_url",
            field=models.URLField(
                blank=True,
                help_text="广告投放链接",
                max_length=500,
                null=True,
                verbose_name="投放链接",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="daily_report_url",
            field=models.URLField(
                blank=True, help_text="任务日报链接", max_length=500, verbose_name="日报链接"
            ),
        ),
    ]
