# Generated by Django 5.0.1 on 2025-03-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0006_task_pixel_task_publish_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="kpi",
        ),
        migrations.RemoveField(
            model_name="task",
            name="operator",
        ),
    ]
