# Generated by Django 5.0.1 on 2025-03-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0007_remove_task_kpi_remove_task_operator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="daily_report_url",
        ),
    ]
