# Generated by Django 5.0.1 on 2025-04-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0008_remove_task_daily_report_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "任务",
                "verbose_name_plural": "任务列表",
            },
        ),
    ]
