# Generated by Django 5.0.1 on 2025-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0009_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="任务所在时区",
                max_length=50,
                null=True,
                verbose_name="时区",
            ),
        ),
    ]
