# Generated by Django 5.0.1 on 2025-05-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0010_task_timezone"),
    ]

    operations = []
