# Generated by Django 5.0.1 on 2025-05-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0012_recreate_task_optimizer_table"),
    ]

    operations = []
