# Generated by Django 5.0.1 on 2025-06-10 08:33

import re
from django.db import migrations, models


def update_sort_numbers(apps, schema_editor):
    """更新现有任务的排序字段"""
    Task = apps.get_model('task_management', 'Task')
    for task in Task.objects.all():
        # 使用正则表达式从名称中提取最后一个连字符后的数字
        match = re.search(r'-(\d+)$', task.name)
        if match:
            task.sort_number = int(match.group(1))
        else:
            # 如果没有匹配到特定模式，尝试提取任何数字作为备选
            numbers = re.findall(r'\d+', task.name)
            if numbers:
                task.sort_number = int(numbers[-1])
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0014_alter_task_optimizer_alter_task_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-sort_number", "-created_at"],
                "verbose_name": "任务",
                "verbose_name_plural": "任务列表",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="sort_number",
            field=models.IntegerField(
                default=0,
                help_text="从任务名称中提取的数字，用于排序",
                verbose_name="排序数字",
            ),
        ),
        migrations.RunPython(update_sort_numbers, migrations.RunPython.noop),
    ]
