# Generated by Django 5.0.1 on 2025-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountConsumption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("card_number", models.IntegerField(verbose_name="卡号")),
                ("expiry_date", models.CharField(max_length=10, verbose_name="有效期")),
                ("cvc", models.IntegerField(verbose_name="CVC")),
                (
                    "full_info",
                    models.CharField(max_length=255, verbose_name="完整信息"),
                ),
                (
                    "responsible_person",
                    models.CharField(max_length=100, verbose_name="用处/责任人"),
                ),
                ("serial_number", models.CharField(max_length=50, verbose_name="编号")),
                ("bm_name", models.CharField(max_length=100, verbose_name="BM名称")),
                ("has_limit", models.CharField(max_length=10, verbose_name="是否限额")),
                ("account_id", models.IntegerField(verbose_name="账户ID")),
                (
                    "account_status",
                    models.CharField(max_length=20, verbose_name="账户状态"),
                ),
                ("card_platform", models.CharField(max_length=50, verbose_name="卡台")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "账户消耗",
                "verbose_name_plural": "账户消耗",
                "ordering": ["-created_at"],
            },
        ),
    ]
