# Generated by Django 5.0.1 on 2025-05-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_consumption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountconsumption",
            name="account_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="账户ID"
            ),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("正常", "正常"),
                    ("待激活", "待激活"),
                    ("已冻结", "已冻结"),
                    ("已关闭", "已关闭"),
                ],
                default="正常",
                max_length=20,
                verbose_name="账户状态",
            ),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="bm_name",
            field=models.CharField(max_length=50, verbose_name="BM名称"),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="card_number",
            field=models.CharField(max_length=50, verbose_name="卡号"),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="card_platform",
            field=models.CharField(max_length=20, verbose_name="卡台"),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="cvc",
            field=models.CharField(max_length=10, verbose_name="CVC"),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="full_info",
            field=models.CharField(max_length=200, verbose_name="完整信息"),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="has_limit",
            field=models.CharField(
                choices=[("是", "是"), ("否", "否")],
                default="否",
                max_length=10,
                verbose_name="是否限额",
            ),
        ),
        migrations.AlterField(
            model_name="accountconsumption",
            name="responsible_person",
            field=models.CharField(max_length=50, verbose_name="用处/责任人"),
        ),
        migrations.CreateModel(
            name="MonthlyConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="消耗金额"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_consumptions",
                        to="account_consumption.accountconsumption",
                        verbose_name="关联账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "月度消耗",
                "verbose_name_plural": "月度消耗",
                "ordering": ["-year", "-month"],
                "unique_together": {("account", "year", "month")},
            },
        ),
    ]
