# Generated by Django 5.0.1 on 2025-04-22 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(max_length=100, verbose_name="渠道名称"),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="消耗"
                    ),
                ),
                (
                    "registrations",
                    models.IntegerField(default=0, verbose_name="注册人数"),
                ),
                (
                    "first_deposits",
                    models.IntegerField(default=0, verbose_name="首充人数"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="预算"
                    ),
                ),
                (
                    "kpi",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="KPI"
                    ),
                ),
                (
                    "budget_description",
                    models.TextField(blank=True, null=True, verbose_name="预算说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "日报数据",
                "verbose_name_plural": "日报数据",
                "ordering": ["-date", "channel_name"],
                "unique_together": {("date", "channel_name")},
            },
        ),
    ]
