# Generated by Django 5.0.1 on 2025-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_report_management", "0002_alter_dailyreport_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
