# Generated by Django 5.0.1 on 2025-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_report_management", "0003_alter_dailyreport_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="daily_recharge_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="当日复充率"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="retention_day2",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="二日留存"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="retention_day3",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="三日留存"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="retention_day4",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="四日留存"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="retention_day5",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="五日留存"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="retention_day7",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="七日留存"
            ),
        ),
    ]
