# Generated by Django 5.0.1 on 2025-04-02 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task_management", "0009_alter_task_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "daily_consumption",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当日消耗"
                    ),
                ),
                (
                    "return_flow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="回流",
                    ),
                ),
                (
                    "actual_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="实际消耗",
                    ),
                ),
                (
                    "registrations",
                    models.IntegerField(blank=True, default=0, verbose_name="注册人数"),
                ),
                (
                    "first_deposits",
                    models.IntegerField(blank=True, default=0, verbose_name="首充人数"),
                ),
                (
                    "impressions",
                    models.IntegerField(blank=True, default=0, verbose_name="展示量"),
                ),
                (
                    "clicks",
                    models.IntegerField(blank=True, default=0, verbose_name="点击量"),
                ),
                (
                    "return_flow_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="回流占比",
                    ),
                ),
                (
                    "click_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="点击转化率",
                    ),
                ),
                (
                    "registration_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="注册转化率",
                    ),
                ),
                (
                    "registration_cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="注册成本",
                    ),
                ),
                (
                    "first_deposit_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="首充转化率",
                    ),
                ),
                (
                    "first_deposit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="首充成本",
                    ),
                ),
                (
                    "click_cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="点击成本",
                    ),
                ),
                (
                    "ecpm",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="每千次展示收益",
                        max_digits=10,
                        verbose_name="ECPM",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_consumptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="task_management.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "消耗明细",
                "verbose_name_plural": "消耗明细",
            },
        ),
    ]
