# Generated by Django 5.0.1 on 2025-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumption_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskconsumption",
            name="installations",
            field=models.IntegerField(blank=True, default=0, verbose_name="安装量"),
        ),
    ]
