# Generated by Django 5.0.1 on 2025-06-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumption_management", "0002_taskconsumption_installations"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskConsumptionMonitor",
            fields=[],
            options={
                "verbose_name": "消耗监控",
                "verbose_name_plural": "消耗监控",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("consumption_management.taskconsumption",),
        ),
    ]
