# Generated by Django 5.1.4 on 2025-02-27 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organize", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaChannel",
            fields=[
                (
                    "MediaChannelID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="渠道ID"
                    ),
                ),
                (
                    "MediaChannelName",
                    models.CharField(max_length=100, verbose_name="渠道名称"),
                ),
                ("Description", models.TextField(blank=True, verbose_name="渠道描述")),
                (
                    "CompanyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organize.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "媒体渠道",
                "verbose_name_plural": "媒体渠道",
                "ordering": ["MediaChannelName"],
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "TaskStatusID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="状态ID"
                    ),
                ),
                (
                    "TaskStatusName",
                    models.CharField(max_length=100, verbose_name="状态名称"),
                ),
                ("Description", models.TextField(blank=True, verbose_name="状态描述")),
                (
                    "CompanyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organize.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务状态",
                "verbose_name_plural": "任务状态",
                "ordering": ["TaskStatusName"],
            },
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "TaskTypeID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="类型ID"
                    ),
                ),
                ("TaskTypeName", models.CharField(max_length=100, verbose_name="类型名称")),
                ("Description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "CompanyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organize.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务类型",
                "verbose_name_plural": "任务类型",
                "ordering": ["TaskTypeName"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "ProjectID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="项目ID"
                    ),
                ),
                ("ProjectName", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "Description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "StartDate",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="开始日期"
                    ),
                ),
                (
                    "EndDate",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "TimeZone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="时区"
                    ),
                ),
                (
                    "KPI",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="KPI"
                    ),
                ),
                (
                    "DailyReportURL",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="日报链接"
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[("进行中", "进行中"), ("已完成", "已完成"), ("已暂停", "已暂停")],
                        default="进行中",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "CompanyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organize.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "ManagerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目负责人",
                    ),
                ),
                (
                    "MediaChannelID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.mediachannel",
                        verbose_name="媒体渠道",
                    ),
                ),
                (
                    "TaskTypeID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.tasktype",
                        verbose_name="任务类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-StartDate"],
            },
        ),
    ]
