# Generated by Django 5.0.1 on 2025-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-StartDate"],
                "verbose_name": "项目列表",
                "verbose_name_plural": "项目列表",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="Pixel",
            field=models.TextField(
                blank=True,
                help_text="用于记录广告像素代码，可能较长",
                null=True,
                verbose_name="广告像素",
            ),
        ),
    ]
