# Generated by Django 5.0.1 on 2025-05-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_project_pixel"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Status2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.taskstatus",
                verbose_name="项目状态2",
            ),
        ),
    ]
