# Generated by Django 5.0.1 on 2025-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_project_status2"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ProductBackend",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="产品后台"
            ),
        ),
    ]
