# Generated by Django 5.0.1 on 2025-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pixel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pixel_id",
                    models.CharField(
                        help_text="像素ID", max_length=100, verbose_name="像素ID"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="任务名称", max_length=200, verbose_name="任务名称"
                    ),
                ),
                (
                    "bm_id",
                    models.CharField(
                        help_text="BM_ID", max_length=100, verbose_name="BM_ID"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True,
                        help_text="账单户或单独账户",
                        max_length=200,
                        null=True,
                        verbose_name="账单户或单独账户",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="账户时区",
                        max_length=50,
                        null=True,
                        verbose_name="账户时区",
                    ),
                ),
                (
                    "is_authorized",
                    models.BooleanField(
                        choices=[(False, "未授权"), (True, "已授权")],
                        default=False,
                        help_text="是否授权",
                        verbose_name="授权状态",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="备注信息", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "像素管理",
                "verbose_name_plural": "像素管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
