# Generated by Django 5.0.1 on 2025-05-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel_management", "0002_pixel_model_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pixel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "像素管理",
                "verbose_name_plural": "像素列表",
            },
        ),
        migrations.AlterField(
            model_name="pixel",
            name="id",
            field=models.BigAutoField(
                help_text="自动生成的ID",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
