# Generated by Django 5.0.1 on 2025-05-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel_management", "0003_alter_pixel_options_alter_pixel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pixel",
            name="bm_id",
            field=models.TextField(
                help_text="BM_ID，支持多条记录，每行一条", verbose_name="BM_ID"
            ),
        ),
        migrations.AlterField(
            model_name="pixel",
            name="pixel_id",
            field=models.TextField(
                help_text="像素ID，支持超长数字", verbose_name="像素ID"
            ),
        ),
    ]
