"""
Django settings for ad_manplat project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hs$^hs$^hs$^hs$^hs$^hs$^hs$^hs$^hs$^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'widget_tweaks',
    'organize.apps.OrganizeConfig',
    'tasks.apps.TasksConfig',
    'task_management.apps.TaskManagementConfig',
    'pixel_management.apps.PixelManagementConfig',
    'consumption_management.apps.ConsumptionManagementConfig',
    'daily_report_management.apps.DailyReportManagementConfig',
    'data_analysis.apps.DataAnalysisConfig',
    'account_consumption.apps.AccountConsumptionConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ad_manplat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'tasks' / 'templates',
            BASE_DIR / 'task_management' / 'templates',
            BASE_DIR / 'pixel_management' / 'templates',
            BASE_DIR / 'consumption_management' / 'templates',
            BASE_DIR / 'data_analysis' / 'templates',
            BASE_DIR / 'account_consumption' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ad_manplat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'zd_db_test_NEW',
        'USER': 'postgres',
        'PASSWORD': 'zhida123',
        'HOST': '154.214.33.123',
        'PORT': '5432',
        'CONN_MAX_AGE': 60,  # 连接最大存活时间（秒）
        'OPTIONS': {
            'connect_timeout': 10,  # 连接超时时间
            'client_encoding': 'UTF8',
            'application_name': 'django',
            'keepalives': 1,           # 启用TCP保活
            'keepalives_idle': 60,     # 空闲60秒后发送保活包
            'keepalives_interval': 10, # 每10秒发送一次保活包
            'keepalives_count': 5,     # 连续5次失败则关闭连接
        },
        # 通过设置ATOMIC_REQUESTS为False减少连接占用时间
        'ATOMIC_REQUESTS': False,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'tasks' / 'static',
    BASE_DIR / 'task_management' / 'static',
    BASE_DIR / 'data_analysis' / 'static',
    BASE_DIR / 'account_consumption' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 自定义用户模型
AUTH_USER_MODEL = 'organize.User'

# SimpleUI Settings
SIMPLEUI_HOME_INFO = False  # 关闭首页信息展示
SIMPLEUI_ANALYSIS = False   # 关闭使用分析
SIMPLEUI_HOME_PAGE = ''     # 不特别指定首页，使用默认
SIMPLEUI_HOME_TITLE = ''  # 首页标题
SIMPLEUI_HOME_ICON = 'fa fa-home'  # 首页图标
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # 默认主题
SIMPLEUI_LOGO = None  # 暂时不设置 logo


# 使用前端框架自带的动态菜单
SIMPLEUI_CONFIG = {
    'system_keep': True,   # 保留系统默认菜单
    'dynamic': True,       # 使用动态菜单
}

# 快速操作
SIMPLEUI_QUICK_ACTIONS = False  # 关闭快速操作

# 移除广告
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False

# 设置主题
SIMPLEUI_DEFAULT_ICON = True  # 默认图标
SIMPLEUI_ICON = {
    '任务管理': 'fas fa-tasks',
    '组织架构': 'fas fa-users-cog',
    '系统管理': 'fas fa-cog',
    'Tasks': 'fas fa-tasks',
    'Organize': 'fas fa-users-cog',
    'Auth': 'fas fa-user-shield',
    '像素管理': 'fas fa-dot-circle',
    '账户管理': 'fas fa-user-circle',
    '日报管理': 'fas fa-calendar-day',
    '数据分析': 'fas fa-chart-line',
    '账户消耗管理': 'fas fa-credit-card'
}

# Admin设置
ADMIN_URL = 'admin/'
LOGIN_URL = '/accounts/login/'  # 前台登录URL
LOGOUT_URL = 'accounts/logout/'

# Admin登录相关设置
ADMIN_LOGIN_URL = '/admin/login/'
ADMIN_LOGOUT_URL = '/admin/logout/'

# 前台登录相关设置
LOGIN_REDIRECT_URL = '/frontend/'  # 前台登录成功后的重定向URL
LOGOUT_REDIRECT_URL = '/accounts/login/'  # 前台登出后的重定向URL

# Admin相关设置
ADMIN_LOGIN_REDIRECT_URL = '/admin/'
